FROM golang:1.26.0

WORKDIR /workspace

RUN apt-get update && \
    apt-get install -y ffmpeg curl && \
    curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp \
    -o /usr/local/bin/yt-dlp && \
    chmod a+rx /usr/local/bin/yt-dlp && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY . .
RUN go work sync
WORKDIR /workspace/downloader-server
EXPOSE 3031
CMD ["go", "run", "."]